project:
  title: "A Beta Way"
  render:
    - ms.qmd

site-url: https://jgeller112.github.io/beta_regression_tutorial/

format:
  apaquarto-pdf:
    documentmode: man
  apaquarto-docx: default
  apaquarto-html:
    toc: true
    toc-depth: 2
    toc-title: Manuscript Outline
    toc-location: right
    echo: true
    code-tools: true
    code-fold: true
    code-summary: "Show R code"

    site-url: https://jgeller112.github.io/beta_regression_tutorial/
  apaquarto-docx:
    comments:
      hypothesis: true
execute: 
  echo: true
